name = "Reagents"
uuid = "88ee5918-12fa-4b16-93fd-f90ded6a9b8c"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.0.1"

[deps]
CompositionsBase = "a33af91c-f02d-484b-be07-31d278c5ca2b"

[compat]
CompositionsBase = "0.1"
julia = "1.7"
