name: Run test via Pkg.test()

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  vanilla-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['~1.7.0-beta3', 'nightly']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: Pkg.test
          name: codecov-umbrella
